=== ViktorPetrina/JAVA2-StarWarsRebellion/xml/dtd/gameMoves.dtd
<!ELEMENT GameMoves (GameMove*)>
        <!ELEMENT GameMove (Planet, Leaders, MoveType, Winner?, Executor)>
        <!ELEMENT Planet (#PCDATA)>
        <!ELEMENT Leaders (Leader*)>
        <!ELEMENT Leader (#PCDATA)>
        <!ELEMENT MoveType (#PCDATA)>
        <!ELEMENT Winner (#PCDATA)>
        <!ELEMENT Executor (#PCDATA)>

=== ViktorPetrina/JAVA2-StarWarsRebellion/xml/gameMoves.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE GameMoves SYSTEM "dtd/gameMoves.dtd">
<GameMoves>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders>
            <Leader>Luke Skywalker</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders>
            <Leader>Leia Organa</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders>
            <Leader>Luke Skywalker</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders>
            <Leader>Leia Organa</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Hoth</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Hoth</Planet>
        <Leaders>
            <Leader>Leia Organa</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Hoth</Planet>
        <Leaders>
            <Leader>Luke Skywalker</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders>
            <Leader>Leia Organa</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders>
            <Leader>Luke Skywalker</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders>
            <Leader>Leia Organa</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders>
            <Leader>Luke Skywalker</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders>
            <Leader>Leia Organa</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders>
            <Leader>Luke Skywalker</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders>
            <Leader>Darth Sidious</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>EMPIRE</Executor>
    </GameMove>
    <GameMove>
        <Planet>Mustafar</Planet>
        <Leaders>
            <Leader>Darth Vader</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>EMPIRE</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders>
            <Leader>Leia Organa</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders>
            <Leader>Luke Skywalker</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders>
            <Leader>Darth Sidious</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>EMPIRE</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders>
            <Leader>Boba Fett</Leader>
        </Leaders>
        <MoveType>DEPLOY</MoveType>
        <Executor>EMPIRE</Executor>
    </GameMove>
    <GameMove>
        <Planet>Tatooine</Planet>
        <Leaders/>
        <MoveType>SECRET_BASE_PICK</MoveType>
        <Executor>REBELLION</Executor>
    </GameMove>
</GameMoves>
